# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/nothing/Tetris/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),Tetris)

$(call add-radio-file-sha1-checked,radio/apusys.img,ed6dd46bf03bebadd1fa414fee75712c0ff9911f)
$(call add-radio-file-sha1-checked,radio/ccu.img,e86290e4a11ad683b582fa878e3cc225288082ac)
$(call add-radio-file-sha1-checked,radio/connsys_bt.img,d1bb71eb53aad7c5baa6f7e92018f5016d69be2e)
$(call add-radio-file-sha1-checked,radio/connsys_gnss.img,8e7f9a00295b72e7e268434492d63b62f2eca3fa)
$(call add-radio-file-sha1-checked,radio/connsys_wifi.img,7c3cc8b5a98e06c329335b9185afe5471db039ed)
$(call add-radio-file-sha1-checked,radio/dpm.img,ee417cb34370b9b3958a1dc904405fe8d1bd452e)
$(call add-radio-file-sha1-checked,radio/gpueb.img,212122f42f68ae457ddc4e31f95aadec143bd7fe)
$(call add-radio-file-sha1-checked,radio/gz.img,14167b4d5b60e7b07dee00c9a7818ea9a8500d2b)
$(call add-radio-file-sha1-checked,radio/lk.img,9fdbe260ce6f43b1e8946da6ed460a094fe0904f)
$(call add-radio-file-sha1-checked,radio/logo.img,0508436b2d946aeb37d6935880f6e1b9f06eddb8)
$(call add-radio-file-sha1-checked,radio/mcf_ota.img,29ec1e552cfb83ecc6283aa71b0bceee338deb3f)
$(call add-radio-file-sha1-checked,radio/mcupm.img,78a5e802b473c84a3652e4a0411bf11da5cf7729)
$(call add-radio-file-sha1-checked,radio/modem.img,89ebfa2406f65b3b20ad0d6e6e147e48e3a259c2)
$(call add-radio-file-sha1-checked,radio/pi_img.img,524935794cc764dfa30d05beb6e5841a5c6aaee4)
$(call add-radio-file-sha1-checked,radio/preloader_raw.img,e0550ce17f8567d0a16243c186a55745ba164b08)
$(call add-radio-file-sha1-checked,radio/scp.img,0a7cbbb4d0942f436bd9622d72f11d4d985942e9)
$(call add-radio-file-sha1-checked,radio/spmfw.img,f67141736cceecda3c6d7e286337f66285b564d0)
$(call add-radio-file-sha1-checked,radio/sspm.img,b7059c9aa88c2f885e4f910361ae1f4057c1cd7b)
$(call add-radio-file-sha1-checked,radio/tee.img,b27fdabe287f0c2fec6da182c0d5d204edf6608a)
$(call add-radio-file-sha1-checked,radio/vcp.img,8ec24b66a1f9f6d7808959bfa1dd0e2cbbef60da)

endif
